### ISSUE TITLE
testSurrogatePairs test fails with 1.9.8 and ICU 60.1

### ISSUE THREAD

**Issue by doko42** [ovalhub/pyicu#61] opened 2017-11-09 07:28 UTC
This test fails for me at least on x86_64:

FAIL: testSurrogatePairs (test_Script.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/packages/tmp/pyicu-1.9.8/build/py2/test/test_Script.py", line 48, in testSurrogatePairs
    self.assertEqual(['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz'], names)
AssertionError: Lists differ: ['Latn', 'Deva', 'Hani', 'Zzzz... != ['Latn', 'Deva', 'Hani', 'Zyyy...

First differing element 3:
'Zzzz'
'Zyyy'

- ['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz']
?                            ^^^     ^^^

+ ['Latn', 'Deva', 'Hani', 'Zyyy', 'Zyyy']
?                            ^^^     ^^^

----------------------------------------------------------------------
Ran 39 tests in 0.351s

FAILED (failures=1)

**Comment by ovalhub** [comment] 2017-11-09 16:42
On Thu, 9 Nov 2017, Matthias Klose wrote:

> This test fails for me at least on x86_64:
>
> FAIL: testSurrogatePairs (test_Script.TestScript)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>  File "/home/packages/tmp/pyicu-1.9.8/build/py2/test/test_Script.py", line 48, in testSurrogatePairs
>    self.assertEqual(['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz'], names)
> AssertionError: Lists differ: ['Latn', 'Deva', 'Hani', 'Zzzz... != ['Latn', 'Deva', 'Hani', 'Zyyy...
>
> First differing element 3:
> 'Zzzz'
> 'Zyyy'
>
> - ['Latn', 'Deva', 'Hani', 'Zzzz', 'Zzzz']
> ?                            ^^^     ^^^
>
> + ['Latn', 'Deva', 'Hani', 'Zyyy', 'Zyyy']
> ?                            ^^^     ^^^

What is your version of Python and what is your locale when this fails ?
This test passes for me on python 2.7.8 and 3.6.0 with
my LANG env var set to en_US.ISO8859-1 (default on my mac).

Andi..

**Comment by doko42** [comment] 2017-11-09 17:08
that's 2.7.14, and 3.6.3. There is LC_ALL=C set.
complete build logs at
https://launchpad.net/ubuntu/+source/pyicu/1.9.8-0ubuntu1

**Comment by ovalhub** [comment] 2017-11-09 19:22
On Thu, 9 Nov 2017, Matthias Klose wrote:

> that's 2.7.14, and 3.6.3. There is LC_ALL=C set.
> complete build logs at
> https://launchpad.net/ubuntu/+source/pyicu/1.9.8-0ubuntu1

I can't reproduce this bug, even when setting LC_ALL=C.
There is not much I can do until I can reproduce this...

**Comment by foutrelis** [comment] 2017-11-12 12:36
The test in question seems to fail on Python 2 only (passes on Python 3).

The above happens with PyICU 1.9.8 and either ICU 59.1 or 60.1, while PyICU 1.9.7 + ICU 59.1 successfully passes all tests.

**Comment by ovalhub** [comment] 2017-11-12 16:48
> On Nov 12, 2017, at 04:36, Evangelos Foutras <notifications@github.com> wrote:
> 
> The test in question seems to fail on Python 2 only (passes on Python 3).
> 
> The above happens with PyICU 1.9.8 and either ICU 59.1 or 60.1, while PyICU 1.9.7 + ICU 59.1 successfully passes all tests.
> 
I can’t reproduce any of the failures. The test passes for me with:
 ICU 59.1 PyICU 1.9.7 Python 2.7 and 3.6
 ICU 60.1 PyICU 1.9.8 Python 2.7 and 3.6
on Mac OS X.

Andi..

**Comment by foutrelis** [comment] 2017-11-12 18:07
Perhaps you're getting Zzzz because your Python 2 uses UCS-2? (Python 2 in Arch Linux is compiled with: --enable-unicode=ucs4)

Related: https://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4

**Comment by doko42** [comment] 2017-11-12 21:05
I think every python2 built for the various Linux distros is built using --enable-unicode=ucs4

**Comment by foutrelis** [comment] 2017-11-12 21:19
Yes, but @ovalhub is on Mac OS X which [seems](https://github.com/pyenv/pyenv/issues/257#issuecomment-250987782) to provide UCS-2 builds of Python 2.

**Comment by ovalhub** [comment] 2017-11-12 23:08
> On Nov 12, 2017, at 10:07, Evangelos Foutras <notifications@github.com> wrote:
> 
> Perhaps you're getting Zzzz because your Python 2 uses UCS-2? (Python 2 in Arch Linux is compiled with: --enable-unicode=ucs4)
> 
> Related: https://stackoverflow.com/questions/1446347/how-to-find-out-if-python-is-compiled-with-ucs-2-or-ucs-4
> 

If that’s the issue then the test should be fixed to check sys.maxunicode and validate the result you’re getting instead of the one I’m seeing.
Could you please provide a simple patch ?

Andi..

**Comment by foutrelis** [comment] 2017-11-25 07:57
sys.maxunicode is the same between Python 3 and UCS-4 Python 2 — yet only the latter produces a test failure. I also confirmed the test passes on a UCS-2 build of Python 2.

It could be that the test is fine but something is wrong in the C code, but I'm not knowledgeable enough to investigate further.

**Comment by ovalhub** [comment] 2017-11-25 14:52
> On Nov 25, 2017, at 04:57, Evangelos Foutras <notifications@github.com> wrote:
> 
> sys.maxunicode is the same between Python 3 and UCS-4 Python 2 — yet only the latter produces a test failure. I also confirmed the test passes on a UCS-2 build of Python 2.
> 
> It could be that the test is fine but something is wrong in the C code, but I'm not knowledgeable enough to investigate further.
> 
I think the code is fine too. It’s just that Python 2 with surrogate pairs is a bit weird and behaves differently when in UCS-4 than UCS-2, iirc.
The test needs to be adapted to this difference instead of failing: if ucs-4 do this else do that.

Andi..

**Comment by mkszuba** [comment] 2018-01-15 08:24
For the record, the problem is still present in 2.0.2.

**Comment by ovalhub** [comment] 2018-01-15 15:25
> On Jan 15, 2018, at 00:24, Marek Szuba <notifications@github.com> wrote:
> 
> For the record, the problem is still present in 2.0.2.
> 
Yes, the issue is still open.  No one with a reproducing system config has proposed a fix so far.

Andi..

**Comment by ovalhub** [comment] 2019-05-24 07:37
fixed (with a workaround since this doesn't reproduce everywhere)

**Closed by ovalhub** 2019-05-24 07:37 UTC
