### ISSUE TITLE
Creation of Collator for Chinese locals fails

### ISSUE THREAD

**Issue by pgammans** [ovalhub/pyicu#6] opened 2015-09-04 09:55 UTC
Creating a Collator and rebuilding from its rules fails for Chinese Collator's

The following code works if you change the locale to `Locale("en", "US", "")` , `Locale("da", "DK", "")` and a few others but not `Locale("zh", "hant", "TW")` , `Locale("zh", "hans", "CN")` , `Locale("zh",  "CN")`

```
import icu
zh_TWCollator= icu.Collator.createInstance(icu.Locale("zh", "TW"))
zh_TWRules = zh_TWCollator.getRules();
newCollator = icu.RuleBasedCollator(zh_TWRules)
```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10

ie this line fails.

```
icu.Collator.createInstance(icu.Locale("zh", "TW"))
```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 34: ordinal not in range(128)

**Comment by ovalhub** [comment] 2015-09-07 00:42
On Fri, 4 Sep 2015, pgammans wrote:

> Creating a Collator and rebuilding from its rules fails for Chinese 
> Collator's
>
> The following code works if you change the locale to `Locale("en", "US", "")` , `Locale("da", "DK", "")` and a few others but not `Locale("zh", "hant", "TW")` , `Locale("zh", "hans", "CN")` , `Locale("zh",  "CN")`
>
> ```
> import icu
> zh_TWCollator= icu.Collator.createInstance(icu.Locale("zh", "TW"))
> zh_TWRules = zh_TWCollator.getRules();
> newCollator = icu.RuleBasedCollator(zh_TWRules)
> ```
> Traceback (most recent call last):
>  File "\<input>", line 1, in \<module>
> ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10
>
>
> ie this line fails.
> ```
> icu.Collator.createInstance(icu.Locale("zh", "TW"))
> ```
> Traceback (most recent call last):
>  File "\<input>", line 1, in \<module>
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 34: ordinal not in range(128)

I can't reproduce this, it works just fine here. What version of PyICU and 
ICU are you using ?

Both this:

   >>> from icu import *
   >>> a=Collator.createInstance(Locale("zh", "TW"))
   >>> len(unicode(a))
   29043

And this:

   >>> from icu import *
   >>> a=Collator.createInstance(Locale("zh", "TW"))
   >>> rules = a.getRules()
   >>> b=RuleBasedCollator(rules)
   >>> len(unicode(b))
   29043

work just fine.

Andi..

**Comment by jwilk** [comment] 2016-07-19 16:08
I can reproduce this using the first @pgammans's example.
That is, for
```python
import icu
zh_TWCollator = icu.Collator.createInstance(icu.Locale("zh", "TW"))
zh_TWRules = zh_TWCollator.getRules();
newCollator = icu.RuleBasedCollator(zh_TWRules)
```
I get:
```pytb
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    newCollator = icu.RuleBasedCollator(zh_TWRules)
icu.ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10
```
This is Python 2.7, ICU 55.1, PyICU 1.9.3.

**Comment by ovalhub** [comment] 2016-07-19 23:23
On Tue, 19 Jul 2016, Jakub Wilk wrote:

> I can reproduce this using the first @pgammans's example.
> That is, for
> ```python
> import icu
> zh_TWCollator = icu.Collator.createInstance(icu.Locale("zh", "TW"))
> zh_TWRules = zh_TWCollator.getRules();
> newCollator = icu.RuleBasedCollator(zh_TWRules)
> ```
> I get:
> ```pytb
> Traceback (most recent call last):
>  File "test.py", line 4, in <module>
>    newCollator = icu.RuleBasedCollator(zh_TWRules)
> icu.ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10
> ```
> This is Python 2.7, ICU 55.1, PyICU 1.9.3.

This is expected as some of the characters in those rules are not printable 
in your default encoding.
The following works for me just fine:

>>> import icu
>>> zh_TWCollator = icu.Collator.createInstance(icu.Locale("zh", "TW"))
>>> zh_TWRules = zh_TWCollator.getRules()
>>> newCollator = icu.RuleBasedCollator(zh_TWRules)
>>> print unicode(newCollator).encode('utf-8')
... lots of output ...

Andi..

**Comment by wfdd** [comment] 2016-07-20 01:09
`icu.RuleBasedCollator(zh_TWRules)` raises so there's no `newCollator` to print.  The Chinese rules contain a whole lotta surrogates, which I haven't seen in any other collator.  These appear to have been added to the CLDR in http://unicode.org/cldr/trac/ticket/2434 (rev 5111).  If you're not experiencing this issue then perhaps you installed ICU4C with pre-generated data.

**Comment by ovalhub** [comment] 2016-07-20 08:53
On Tue, 19 Jul 2016, [??ufd?] wrote:

> `icu.RuleBasedCollator(zh_TWRules)` raises so there's no `newCollator` to 
> print.

Clearly but the exception it actually raises may be hidden by the exception 
piled on while failing to print it.

If you can reproduce this bug, can you try to catch the exception and print 
it with a unicode(exception).encode('utf-8') trick to workaround the 
unprintable-in-default-encoding issue most liking obfuscating it ?

> The Chinese rules contain a whole lotta surrogates, which I 
> haven't seen in any other collator.  These appear to have been added to 
> the CLDR in http://unicode.org/cldr/trac/ticket/2434 (rev 5111).  If 
> you're not experiencing this issue then perhaps you installed ICU4C with 
> pre-generated data.

Not sure what you mean by 'pre-generated' data. I built ICU 57.1 from 
sources as downloaded from the ICU site.

Andi..

**Comment by pgammans** [comment] 2016-07-20 09:34
Sorry about large delay in responding, I had hopped that I'd upgraded my system as I think it related to the version of ICU i'm using.
Python 2.7.3, pyICU 1.4, ICU 4.8.1 (from debian)

@ovalhub your first test's 
The length of 'a' was 16227 not 29043 as per your example.

b failed on the line ```b=RuleBasedCollator(rules)```  with the exception 
```
 Traceback (most recent call last):
  File "<input>", line 1, in <module>
ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10
```

**Comment by wfdd** [comment] 2016-07-20 09:54
> Clearly but the exception it actually raises may be hidden by the exception
> piled on while failing to print it.

It fails before actually attempting to print it:

```py
In [1]: import icu, sys

In [2]: zh_TWCollator = icu.Collator.createInstance(icu.Locale("zh", "TW"))

In [3]: zh_TWRules = zh_TWCollator.getRules()

In [4]: newCollator = icu.RuleBasedCollator(zh_TWRules)
---------------------------------------------------------------------------
ICUError                                  Traceback (most recent call last)
<ipython-input-4-f60a2f78d633> in <module>()
----> 1 newCollator = icu.RuleBasedCollator(zh_TWRules)

ICUError: Character conversion: Unmappable input sequence. In other APIs: Invalid character., error code: 10

In [5]: sys.version, icu.VERSION, icu.ICU_VERSION
Out[5]: 
('3.5.2 (default, Jun 29 2016, 23:50:40) \n[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]',
 '1.9.3',
 '57.1')
```

> Not sure what you mean by 'pre-generated' data. I built ICU 57.1 from
> sources as downloaded from the ICU site.

The ICU folk provide a precompiled data archive (http://site.icu-project.org/download/57#TOC-ICU4C-Download); oddly, the collations in that archive don't contain these suspect surrogate pairs.

**Comment by ovalhub** [comment] 2016-12-20 01:37
This seems to work since the UnicodeString <-> unicode rework in PyICU 1.9.5.
Closing. Please, reopen if you can still reproduce the problem.

**Closed by ovalhub** 2016-12-20 01:37 UTC
