### ISSUE TITLE
PyICU 2.4.1 compilation failure on macOS 10.14.6

### ISSUE THREAD

**Issue by manselmi** [ovalhub/pyicu#115] opened 2019-11-12 13:40 UTC
Hi, and thanks for maintaining PyICU!

I am reporting a PyICU 2.4.1 compilation failure on macOS 10.14.6, using ICU 64.2 provided by Homebrew. When running `pip install PyICU` I see the following error:

```
ERROR: Command errored out with exit status 1:
 command: /Users/manselmi/virtualenv/default-py37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-install-adcd5j6e/PyICU/setup.py'"'"'; __file__='"'"'/private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-install-adcd5j6e/PyICU/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-record-a2uy1img/install-record.txt --single-version-externally-managed --compile --install-headers /Users/manselmi/virtualenv/default-py37/include/site/python3.7/PyICU
     cwd: /private/var/folders/tg/06ncct7j4b74t13k0fp8h9sd9w0tnj/T/pip-install-adcd5j6e/PyICU/
Complete output (28 lines):
(running 'icu-config --version')

Building PyICU 2.4.1 for ICU 64.2

(running 'icu-config --cxxflags --cppflags')
Adding CFLAGS="-std=c++11 -I/Users/manselmi/.prefix/sw/homebrew/Cellar/icu4c/64.2/include" from /Users/manselmi/.prefix/bin/icu-config
(running 'icu-config --ldflags')
Adding LFLAGS="-L/Users/manselmi/.prefix/sw/homebrew/Cellar/icu4c/64.2/lib -licui18n -licuuc -licudata" from /Users/manselmi/.prefix/bin/icu-config
running install
running build
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
copying PyICU.py -> build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/icu
copying icu/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/icu
running build_ext
building '_icu' extension
creating build/temp.macosx-10.7-x86_64-3.7
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/manselmi/.prefix/sw/miniconda/include -arch x86_64 -I/Users/manselmi/.prefix/sw/miniconda/include -arch x86_64 -I/Users/manselmi/virtualenv/default-py37/include -I/Users/manselmi/.prefix/sw/miniconda/include/python3.7m -c _icu.cpp -o build/temp.macosx-10.7-x86_64-3.7/_icu.o -std=c++11 -I/Users/manselmi/.prefix/sw/homebrew/Cellar/icu4c/64.2/include -DPYICU_VER="2.4.1"
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from _icu.cpp:27:
In file included from ./common.h:106:
/Users/manselmi/.prefix/sw/homebrew/Cellar/icu4c/64.2/include/unicode/unistr.h:31:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1
```

**Comment by ovalhub** [comment] 2019-11-12 16:51
Did you try what the error message suggested ?
"warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]" ?
Somehow, your C++ compiler is not functional.

Andi..

**Comment by ovalhub** [comment] 2019-11-12 23:26
this looks like a duplicate of #110

**Closed by ovalhub** 2019-11-12 23:26 UTC
